version: '3'
services:
   redis: 
      image: redislabs/redismod
      ports:
         - '6379:6379'

   web:
      build: .
      ports:
         - '5001:5001'
      volumes:
        - .:/code
      depends_on:
         - redis
